### ISSUE TITLE
Releas as a .deb package

### ISSUE THREAD

**Issue by sbstn87** [Picocrypt/Picocrypt#10]
Hi,

will it be possible to release Picocrypt also as a .deb package for an easy installation on Debian and its derivatives without using Snap?

**Comment by sbstn87** [comment]
By the way, releasing as a .deb package would make it possible to add Picocrypt to deb-get:

https://github.com/wimpysworld/deb-get

**Comment by hakavlad** [comment]
BTW it's easy: write simple `Makefile` and simple `DEBIAN/control` file. Then run something like `make deb`.

**Comment by HACKERALERT** [comment]
I used to have a .deb, I think we can just download it and update the binary inside:

https://github.com/HACKERALERT/Picocrypt/releases/download/1.29/Picocrypt.deb

You can extract it with 7-zip to get the files.

I forget what the exact process to making it was, though this may help:

https://github.com/HACKERALERT/Picocrypt/issues/84#issuecomment-1114368398

I used to have Picocrypt on deb-get, but I stopped maintaining the .deb so it was probably removed. You guys are welcome to try to get it back on there if you can create a .deb.

So in all, three possible improvement tasks:
1. Create a .deb using the previous .deb as a reference. How we will release this securely is still to be figured out, but I will try my hand at some github actions.
2. Get it onto deb-get
3. Add the .deb source/config files into the GitHub repo for easy access, also maybe create a dist/deb/README to describe how to build it. You guys are free to decide how to do this if you choose to do it

BTW if you ever need me, please feel free to just ping as I have notifs for this repo as mentions only at the moment to focus on other things so I don't see these unless I manually come and check.

**Comment by HACKERALERT** [comment]
GitHub Actions compiling for windows successfully 🥳 

I will try to add Linux and macOS as well eventually

**Comment by sbstn87** [comment]
Perhaps you could use Open Build Service for automated builds?

https://build.opensuse.org/

**Comment by HACKERALERT** [comment]
Ideally everything stays on GitHub for easy access and transparency. If GitHub Actions can compile automatically, no need to use an external service.

**Comment by HACKERALERT** [comment]
@sbstn87 @hakavlad 
first attempt at github actions for linux. Does this raw binary run for you guys?

https://github.com/Picocrypt/Picocrypt/actions/runs/9590610901/artifacts/1619014523

**Comment by hakavlad** [comment]
>https://github.com/Picocrypt/Picocrypt/actions/runs/9590610901/artifacts/1619014523

```
$ ./Picocrypt
./Picocrypt: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by ./Picocrypt)
./Picocrypt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./Picocrypt)
./Picocrypt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by ./Picocrypt)
./Picocrypt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./Picocrypt)
./Picocrypt: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./Picocrypt)
```
As expected for me.

**Comment by HACKERALERT** [comment]
@hakavlad try again, I dropped the Ubuntu version down to 22

**Comment by HACKERALERT** [comment]
The latest build-linux artifact

**Comment by hakavlad** [comment]
>https://github.com/Picocrypt/Picocrypt/actions/runs/9590610901/artifacts/1619014523

```
$ ./Picocrypt
./Picocrypt: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by ./Picocrypt)
./Picocrypt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./Picocrypt)
./Picocrypt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by ./Picocrypt)
./Picocrypt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./Picocrypt)
./Picocrypt: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./Picocrypt)
```

**Comment by HACKERALERT** [comment]
Hmm debian 11 should match Ubuntu 22. Anyways I've dropped it down to Ubuntu 20. Try the latest artifact and also try installing the packages listed in src/readme for Linux

**Comment by hakavlad** [comment]
https://github.com/Picocrypt/Picocrypt/suites/25104041135/artifacts/1619014523

not found

**Comment by hakavlad** [comment]
Latest works with GUI!

**Comment by HACKERALERT** [comment]
Ayy nice. Do you think I should keep the Ubuntu at 20 or to 24? Both work, not sure which to pick.

**Comment by hakavlad** [comment]
Ubuntu 20.04 is still supported. Selecting the latest version will make the package useless for some users.

**Comment by hakavlad** [comment]
with previous build
```
$ ./Picocrypt
./Picocrypt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./Picocrypt)
./Picocrypt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./Picocrypt)
./Picocrypt: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./Picocrypt)
```
my is 2.31

**Comment by sbstn87** [comment]
> Latest https://github.com/Picocrypt/Picocrypt/actions/runs/9597712710 works with GUI!

Works for me with a GUI on Debian 12 (Stable). I have successfully encrypted and decrypted a file with it.

**Comment by HACKERALERT** [comment]
Sounds good, I'll keep it on Ubuntu 20 for now. I'll try to add making a .deb to the workflow in the next few days

**Comment by HACKERALERT** [comment]
@sbstn87 @hakavlad 
does this .deb work?

https://github.com/Picocrypt/Picocrypt/actions/runs/9607527617/artifacts/1623262789

**Comment by sbstn87** [comment]
> @sbstn87 @hakavlad does this .deb work?
> 
> https://github.com/Picocrypt/Picocrypt/actions/runs/9607527617/artifacts/1623262789

The package installed successfully, without any errors and can be found in the Applications Menu, but the app does not start on Debian 12.

**Comment by hakavlad** [comment]
>Depends: libc6, libgcc-s1, libgl1, libgtk-3-0, libstdc++6, libx11-6, xclip

It would be good to specify minimum versions.

**Comment by hakavlad** [comment]
>/usr/local/bin/Picocrypt

It would be good to install in /usr/bin, not local.

**Comment by hakavlad** [comment]
> does this .deb work?

Works with GUI, no problem.

**Comment by hakavlad** [comment]
app does not start FROM APP MENU, but no problem with 
```
$ Pycocrypt
```

**Comment by HACKERALERT** [comment]
🤪 forgot about that, I'll fix it soon. I'm thinking of renaming to picocrypt-gui as well so it doesn't conflict with the CLI.

**Comment by HACKERALERT** [comment]
> It would be good to specify minimum versions.

Don't know how to get the package versions lol. I think it's okay, the packages have been around for a while and the latest on any Ubuntu version 20+ will suffice.

> It would be good to install in /usr/bin, not local.

Got it.

@hakavlad @sbstn87 Sorry for the pings, hopefully this will be the last or second last. Here's another attempt:

https://github.com/Picocrypt/Picocrypt/actions/runs/9621888512/artifacts/1626823619

**Comment by hakavlad** [comment]
dpkg-deb: error: archive "/tmpfs/Picocrypt.deb" uses unknown compression method for "control.tar.zst", discontinue

maybe replace zstd by older way, tar.gz

**Comment by HACKERALERT** [comment]
huh where is this error coming from?

**Comment by HACKERALERT** [comment]
ok a google search and it says zstd isn't in debian 11 but is in 12. i never told dpkg-deb to use zstd though 🤷 . It's okay, as long as the binary works on 11, I'm fine with the .deb requiring 12. So @sbstn87 theoretically should be able to install the latest .deb artifact

**Comment by hakavlad** [comment]
https://stackoverflow.com/questions/71196872/how-do-i-build-a-deb-without-zstd-compression-in-ubuntu-21-10

```
       -Zcompress-type
           Specify which compression type to use when building a
           package.  Allowed values are gzip, xz (since dpkg 1.15.6),
           zstd (since dpkg 1.21.18) and none (default is xz).
```
https://man7.org/linux/man-pages/man1/dpkg-deb.1.html

Just replace 
```
        dpkg-deb --build --root-owner-group Picocrypt
```
with
```
        dpkg-deb -Zxz --build --root-owner-group Picocrypt
```
I believe that changing the compression method will not greatly affect the package size.

**Comment by sbstn87** [comment]
> @hakavlad @sbstn87 Sorry for the pings, hopefully this will be the last or second last. Here's another attempt:
> 
> https://github.com/Picocrypt/Picocrypt/actions/runs/9621888512/artifacts/1626823619

It installed successfully on Debian 12. Works both when launched form the app menu and from CLI as picocrypt-gui.

**Comment by HACKERALERT** [comment]
Awesome. Anything else you want or need, or are we good here?

**Comment by sbstn87** [comment]
Seems good.

What remains to be done is putting Picocrypt on deb-get.

**Comment by HACKERALERT** [comment]
Hmmm but artifacts don't have a stable url. So I don't think we can get it on deb-get, which is fine I think. It would be cool if we can get it in the standard debian repos, but that's for another day.

**Comment by sbstn87** [comment]
I meant, putting on on deb-get when a new release with a .deb package provided is available :)

**Comment by HACKERALERT** [comment]
I don't plan on making full releases anymore, I was thinking of a nightly release schedule. The GitHub Actions are already scheduled to run every night so there's no need for full releases anymore.

**Comment by sbstn87** [comment]
Great to hear that. Please let us know when it's completed.

**Comment by hakavlad** [comment]
The latest build https://github.com/Picocrypt/Picocrypt/actions/runs/9630169881
doesn't work on Debian 11
```
$ ./Picocrypt
./Picocrypt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./Picocrypt)
./Picocrypt: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./Picocrypt)
./Picocrypt: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by ./Picocrypt)
```

**Comment by HACKERALERT** [comment]
@hakavlad @sbstn87 @CodeCracker-oss @valynor @ZingyAwesome @dsm @ANiceCupOfTea

Please try the latest nightly build in the Releases tab and let me know whether they work via a reaction:
`Picocrypt`: 1️⃣ 
`Picocrypt.deb`: 2️⃣ 
`Picocrypt.dmg`: 3️⃣  
`Picocrypt.exe`: 4️⃣

**Comment by ANiceCupOfTea** [comment]
MacOS version is working fine. Thanks!

I know you have said you're not interested in actively developing Picocrypt anymore but I think there is still plenty of mileage left in it if you ever reconsider. Even just some UI tweaks like displaying the version number and GitHub link on the 'About' window popup would be useful. Also, finding a way to include the full descriptions of all of the advanced options so new users don't have to refer to the GitHub page would be cool.

I love the app and appreciate all the time and effort you have put into developing it. Thank you!

**Comment by HACKERALERT** [comment]
Now that there's a stable url for the nightly .debs, I think we can get Pico back on deb-get again. Can someone do that? Would be nice for small things like these to have some helping hands.

**Comment by HACKERALERT** [comment]
Also, if anyone knows a Debian package maintainer, we could give a go at getting Pico into official Debian repos. Not easy for sure, but a cool goal to have in mind.

**Comment by sbstn87** [comment]
> Now that there's a stable url for the nightly .debs, I think we can get Pico back on deb-get again. Can someone do that? Would be nice for small things like these to have some helping hands.

Done:

https://github.com/wimpysworld/deb-get/issues/1114

**Comment by HACKERALERT** [comment]
Awesome, thanks.

**Comment by philclifford** [comment]
> I don't plan on making full releases anymore, I was thinking of a nightly release schedule. This (and the hard-coding version as 1) will probably preclude adding back to `deb-get`
Please see 
https://github.com/wimpysworld/deb-get/issues/1114#issuecomment-2191710442

Hope you can understand why, and can consider tweaking your automations to make it possible.

**Comment by HACKERALERT** [comment]
Changes made, releases are now tagged like before (1.34, etc.). The orignal reason for nightly releases is because I didn't know how to version it lol. But I had a big brain moment and realized I can store the version in a VERSION file and only run the GH Actions when I push to that VERSION file. Then just extract the version text from the file and set it as the tag name.

Going to remove nightly releases. Stable, tagged releases are a better idea especially for something security/stability critical like Picocrypt.
