### ISSUE TITLE
Modularize and add tests

### ISSUE THREAD

**Issue by HACKERALERT** [Picocrypt/Picocrypt#16]
This is a big one. We should try to split the single massive source file into smaller, reusable components so that we have cleaner code and can add unit tests/suites. These tests will further ensure reliability of the software.

**Comment by HACKERALERT** [comment]
If you want to take a stab at this, please do so in the Experiments repository. Only when it is production ready should you try to merge things back into this main core repository.

**Comment by njhuffman** [comment]
I started an attempt at this here, still very much wip
https://github.com/Picocrypt/Experiments/tree/stand-alone-backend

**Comment by HACKERALERT** [comment]
This is incredible work, great job! Really excited to see where this goes. Keep at it and take your time, when you feel like you're getting to a somewhat stable state, ping me and I'll do a careful code review and then decide how to get things into production safely.

**Comment by HACKERALERT** [comment]
Wow, great idea on the reed Solomon compromise. Love the idea of a one pass solution that isn't slow as molasses. Just make sure that RS is deterministic, ie same inputs will always have same outputs. I believe that is the case since there is no randomness going into the encoding, so your idea should work in theory.

Another idea for tests, we can make a bunch of volumes in the current gui and make sure the rewrite still can decrypt then.

**Comment by HACKERALERT** [comment]
Also wow, very good job on the file organization. Intuitive and clean, love it.

**Comment by HACKERALERT** [comment]
As a general note, would be a good idea to use builtins where possible for performance. For example, arrMatch is the same as bytes.Equal, min can be math.Min

Just small nitpicks, don't worry about them now, putting here so I remember for future code reviews

**Comment by njhuffman** [comment]
Thanks, missed the bytes builtin somehow. First time using go so still feeling out what's already there.

**Comment by HACKERALERT** [comment]
Pretty impressive code for a new Go user, faster learner than me :)

**Comment by HACKERALERT** [comment]
@njhuffman just wanted to let you know, we recently raised enough money for an audit for the desktop app. After the audit, no major code changes must be made otherwise it would invalidate the audit. So this issue would be more like creating a shared core library for CLI, web, and mobile apps to use in the future. Feel free to stop working on this completely if your goal was to get it into the desktop app, or if you think you've had enough of Go 🤪

**Comment by HACKERALERT** [comment]
Closing for now as the audit as completed and I likely won't make any major changes unless a big issue arises.
