### ISSUE TITLE
Comments and Deniability

### ISSUE THREAD

**Issue by hakavlad** [Picocrypt/Picocrypt#24]
Comments with enabled Deniability are not displayed during decryption.

Is it possible to more clearly inform the user through the app window that comments will be lost if Deniability is enabled?

**Comment by HACKERALERT** [comment]
Noting it in the README is definitely something to do. PRs welcome. For the app, we could add additional info the the deniability hover tooltip, or completely clear and disable the comments section if a user clicks on Deniability. Either is good with me.

@njhuffman Seems a bit niche, but could be straightforward to implement with your rewrite. Feel free to add small things like these to your refactor. For the single source file, I think we can skip for the time being.

**Comment by Retengart** [comment]
Maybe something like that will be more explicit
![image](https://github.com/user-attachments/assets/f81157ba-861b-4277-a382-2872c3499622)


> Comments with enabled Deniability are not displayed during decryption.
> 
> Is it possible to more clearly inform the user through the app window that comments will be lost if Deniability is enabled?

**Comment by Retengart** [comment]
https://github.com/user-attachments/assets/9846b585-5ca7-46ff-949b-72ebf1c3f807

**Comment by HACKERALERT** [comment]
I think you had a PR for this, so this issue is good to close right?

**Comment by Retengart** [comment]
Yeah, that's right.
