### ISSUE TITLE
Keyfile size

### ISSUE THREAD

**Issue by hakavlad** [Picocrypt/Picocrypt#25]
Picocrypt creates 1 KiB keyfiles. Although there is no reason to create a file larger than 32 (256 bit) or 64.
Using large keyfile increases the risk of file corruption due to [bit rot](https://en.wikipedia.org/wiki/Data_degradation).
Suggestion: create 64 B files instead of 1 KiB.

**Comment by HACKERALERT** [comment]
@hakavlad Agreed! It's a small change, would anyone be willing to submit a PR changing the random keyfile size to 32 bytes?

https://github.com/Picocrypt/Picocrypt/blob/main/src/Picocrypt.go#L448

Just change "KiB" to "32" and add me as a reviewer to the PR. Thanks!

**Comment by hakavlad** [comment]
merged https://github.com/Picocrypt/Picocrypt/pull/26
