### ISSUE TITLE
"Removing deniability protection..." predates "Deriving key..." (according to the GUI messages)

### ISSUE THREAD

**Issue by hakavlad** [Picocrypt/Picocrypt#27]
Expected: deriving keys (XChaCha20 internal key, Serpent key, XChaCha20 external key, MAC key from non-overlapping parts of the Argon2 output), and only then using these keys.

Demo: https://youtu.be/7LrS9ZB0038?si=EEg6YG4_LTDWoCTl&t=85

**Comment by HACKERALERT** [comment]
Deniability works be reencrypting with a different key. So it can't get the original volume keys unless it removes that deniability layer. Thus it removes deniability first and then derives keys like a normal volume. I don't think there is any performance benefit to removing deniability to get the header and derive keys first, so don't see this as an issue other than being slightly unintuitive perhaps.

**Comment by hakavlad** [comment]
I would just like to understand how you get the keys to remove deniability. What parameters does Argon start with? If Argon is launched, then why is this not reported through the GUI?

**Comment by HACKERALERT** [comment]
https://github.com/Picocrypt/Picocrypt/blob/main/Internals.md#deniability

Same parameters as regular Argon2, 4 passes, 4 threads. Not shown in the GUI because I was lazy, didn't see the need to add text for something that takes less than a second on most machines.

**Comment by hakavlad** [comment]
OK thanks!
