### ISSUE TITLE
Intel version for Mac

### ISSUE THREAD

**Issue by pionl** [Picocrypt/Picocrypt#31]
Hi,

I wanted to test the app on Mac but could not find latest version being built for Intel (only for Apple silicon). Is this bug ?

I've found in changelog that from 04/29/2024 (v1.34) should contain both platforms (but no success on this version too).

Thank you for your time,

<img width="137" alt="Snímek obrazovky 2024-07-10 v 11 31 46" src="https://github.com/Picocrypt/Picocrypt/assets/1878831/9d9bf628-58cb-4069-ada8-87162d0e9533">

**Comment by HACKERALERT** [comment]
In the old HACKERALERT/Picocrypt repo there are Intel builds. When moving to here, though, I decided to clean things up a bit since it's been 4 years since the first Apple silicon and Intel macs will go out of support from Apple in 2 or 3 years. The old 1.33 version works totally fine, no need to move to 1.34/37 at the moment.

**Comment by m04ndj5xc2u3pn4eow** [comment]
Hi @HACKERALERT – I recently found out about this encryption tool, awesome project! 

I, too, have an Intel Mac (running Sonoma 14.7) and can't install this tool. Possible to upload a 1.43 Intel version .dmg?

Thank you!

**Comment by Retengart** [comment]
@m04ndj5xc2u3pn4eow , https://github.com/HACKERALERT/Picocrypt/releases/tag/1.33

**Comment by m04ndj5xc2u3pn4eow** [comment]
Thanks for your reply @HACKERALERT ! Much appreciated for the link.

I see the sec audit happened at commit 7e403a2e57d3f639e00bd82e356cd393e646fe01 and the last release for x86 was before that.

I did see your note of taking a break from this project, so if a 1.43 Intel release is not possible, I'll look for other options.

Thanks again!

**Comment by HACKERALERT** [comment]
The audit did not discover anything significant other than not catching potential rng errors, which is highly unlikely in a popular OS like macOS. The format and header has not changed either so 1.33 and 1.43 produce the exact same output and behave similarly. You can use the 1.33 version perfectly fine without worries.

**Comment by m04ndj5xc2u3pn4eow** [comment]
Great! Thanks for the explanation and reply @HACKERALERT 👍
