### ISSUE TITLE
return of metadefender...

### ISSUE THREAD

**Issue by DeMarskman** [Picocrypt/Picocrypt#33]
I don't know if it's important but the new portable version raises a Security alert (True or false???)

![foto_no_exif](https://github.com/user-attachments/assets/949344b9-3e3e-4ce0-a9d6-59cd0a3dbd6e)

**Comment by hakavlad** [comment]
see https://github.com/HACKERALERT/Picocrypt/issues/146

**Comment by HACKERALERT** [comment]
Pretty normal by now, there's always one or two funky scan engines. In the old repo, there was reason for people to be suspicious since I made the builds manually, but everything is automated now and builds are done by GitHub Actions, not me, so you can trust that it is safe.
