### ISSUE TITLE
special requirements under Windows 11 ?

### ISSUE THREAD

**Issue by patatetom** [Picocrypt/Picocrypt#34]
hi,

does `Picocrypt` have any special requirements under Windows 11 ?

I'm desperately trying to run `Picocrypt.exe` (1.37 / 3bbf02b17fddccb087dc768ba8431e548460e413a208795301d4b15ee19dc98b) in a Windows 11 virtual machine (23H2) but nothing happens : the 'hourglass' runs for a few moments and then nothing.

no error is displayed if run from a command prompt.
nothing in the system logs either.

same behavior with Windows Defender deactivated.
same behavior when starting `Picocrypt` as administrator.

regards, lacsaP.

**Comment by patatetom** [comment]
thanks for the leads: here's a little feedback.

the use of the above DLLs did not make `Picocrypt 1.37` downloaded from `GitHub/Picocrypt/` work.

on the other hand, `Picocrypt 1.33` works perfectly when installed with the installer downloaded from `GitHub/HACKERALERT/`.

the copy of `Picocrypt 1.33` (eg. of the installation folder) continues to work after `Picocrypt 1.33` has been uninstalled.

`Picocrypt 1.33` (delivered alone from `GitHub/HACKERALERT/`) works if placed in the copied folder, alongside the 3 DLLs (see screenshot).

`Picocrypt 1.34`, `Picocrypt 1.35`, `Picocrypt 1.36` and `Picocrypt 1.37` (delivered alone from `GitHub/Picocrypt/`) do not work if placed in the copied folder, alongside the 3 DDLs (see screenshot).

adding `dxil.dll` (present in `mesa-d3d12-x64-24.1.4.zip`) changes nothing 

for information, this is a fresh install of Windows 11.

regards, lacsaP.

![2024 07 30-09 27 02](https://github.com/user-attachments/assets/8b5bd008-785e-4fe3-85ab-0914d8787b04)

**Comment by HACKERALERT** [comment]
I'm not sure how what's happening, 1.34 and on are produced by GitHub Actions but mirror the process I used for 1.33. Maybe someone else can help debug, but otherwise feel free to stick with 1.33 Installer.exe, not much changed and it's perfectly fine to use.

**Comment by HACKERALERT** [comment]
https://github.com/Picocrypt/Picocrypt/releases/download/1.43/Paranoid.zip

The exe inside here will very likely work.

**Comment by patatetom** [comment]
for your information: 
I was unable to run it on a freshly installed Windows 11 24H2 in a virtual machine.
I added the advanced DLLs earlier but it didn't make any difference.
I haven't tested it on other versions of Windows.

here are the events and error file generated :
[picocrypt.zip](https://github.com/user-attachments/files/17894357/picocrypt.zip)

**Comment by Retengart** [comment]
@patatetom try the opengl-integrated picocrypt build, maybe it'll work somehow
https://github.com/orgs/Picocrypt/discussions/61#discussioncomment-10710201

**Comment by patatetom** [comment]
the problem encountered from version 1.35 is related to the lack of functionality on the microprocessor side : `picocrypt.exe` (1.35->1.44) works perfectly by adding the `ssse3` and `sse4.1` flags to the emulated microprocessor (`qemu64` - _I thought that the sse4.2 feature would de facto entail the previous ones, but that doesn't seem to be the case_).

in my Windows 11 virtual machine, the two libraries `opengl32.dll` and `dxil.dll` (from `mesa-d3d12-x64-24.1.4.zip`) are still essential for `picocrypt.exe` to function.

since version 1.35, the product version no longer appears in `picocrypt.exe` (file explorer / properties / details tab) : _although it can be accessed from there (if registered), it might be a good idea to display it in the GUI (in the status bar, for example)._

the `Deniability` checkbox deletes any comments entered : _it would be a plus if it could be saved and reintroduced when the function is unchecked._

regards, lacsaP.
