### ISSUE TITLE
add to homebrew?

### ISSUE THREAD

**Issue by felixsanz** [Picocrypt/Picocrypt#41]

**Comment by HACKERALERT** [comment]
Would be cool. If you know any homebrew maintainers that might be able to help, please do link them here.

**Comment by felixsanz** [comment]
Is this useful? https://docs.brew.sh/Adding-Software-to-Homebrew

**Comment by HACKERALERT** [comment]
I don't have a Mac so I can't test it if I did come up with a prototype 😅

**Comment by felixsanz** [comment]
brew is also a tool for linux and windows, so the whole process of creating the package can be tested in this machines, the only related part to Mac is the package in some architecture (silicon, etc), right? I'm very newbie here so maybe is not that easy

**Comment by HACKERALERT** [comment]
There is no brew for Windows, only Linux and Mac. I can do it on Linux, but it would be blindfolded without a way to test. Imo not a big priority, like flatpak, if someone comes along and can figure it out, great, otherwise the app still runs fine without a package manager.

**Comment by dsm** [comment]
brew official repo wants macos app signed and notarized so you need apple developer account but you can create an own brew tap in your repo. I make this for qucs-s program https://github.com/ra3xdh/homebrew-qucs-s

**Comment by HACKERALERT** [comment]
Apple ☹️

**Comment by iPyGuy** [comment]
I [submitted a PR](https://github.com/Homebrew/homebrew-cask/pull/184127) to add it to brew casks but it was rejected since the app isn’t notarized as @dsm mentioned. 😟

**Comment by HACKERALERT** [comment]
Thanks for the attempt. Unfortunately I don't have $99 a year to spare to Apple to sign an app 😂

**Comment by vraravam** [comment]
Created a [homebrew tap](https://github.com/vraravam/homebrew-picocrypt)

**Comment by HACKERALERT** [comment]
Thanks for the help! Can someone other than @vraravam give the homebrew tap a try? Let me know. If so, I might fork your repo into the Picocrypt org.

**Comment by vraravam** [comment]
> Thanks for the help! Can someone other than [@vraravam](https://github.com/vraravam) give the homebrew tap a try? Let me know. If so, I might fork your repo into the Picocrypt org.

At this point, the repo can also remain as-is (under my id) - but, I will be glad to donate it to your org as well. The SHA/version will keep needing to be updated for each release - so there's that extra small overhead to do as well.

**Comment by vraravam** [comment]
Since this is now created in the picocrypt org, I have deleted my repo. This makes the fork a top-level repo ie without a "forked from" line.

**Comment by HACKERALERT** [comment]
Awesome. So I'm assuming `--no-quarantine` does the `xattr` command?

**Comment by HACKERALERT** [comment]
So this would be good to add to the README I'm assuming.

![Image](https://github.com/user-attachments/assets/ec2299b1-5a5b-4d2e-b218-99abe4d4e92a)

**Comment by dsm** [comment]
> Awesome. So I'm assuming `--no-quarantine` does the `xattr` command?

Yes

**Comment by HACKERALERT** [comment]
Okay, I'm going to merge. Feel free to reopen this and ping me if there are any issues.

**Comment by iPyGuy** [comment]
Sorry for the slightly late response but yeah, it works here without any problems!

**Comment by avocadoattack** [comment]
Hello! I attempted to install Picocrypt via the provided Homebrew tap, but I receive the following error:

`Error: Cask 'picocrypt' definition is invalid: invalid 'sha256' value: nil`

Any help is greatly appreciated 😊 @vraravam @HACKERALERT 

![Image](https://github.com/user-attachments/assets/0953b3a2-9b55-41da-a36d-622476023b35)

**Comment by HACKERALERT** [comment]
Ah that's the reason, only Apple silicon is officially supported and has a release, so homebrew must have been looking for an amd64 file/sha256 but found none.

I don't plan to add back Intel support since most Intel Macs are nearing the end of software support within the next year or two.

**Comment by avocadoattack** [comment]
Ah! Thanks for the heads up. I understand your decision to not support Intel-based Macs. Either way, thanks for the tip on building from source myself! And thanks for creating and maintaining Picocrypt!

**Comment by HACKERALERT** [comment]
I plan to stop working on Picocrypt and freeze everything, so I'm trying to make things minimal. The homebrew tap is just a wrapper around the .app so I decided to stick with .app only.

**Comment by vraravam** [comment]
> I plan to stop working on Picocrypt and freeze everything, so I'm trying to make things minimal. The homebrew tap is just a wrapper around the .app so I decided to stick with .app only.

oh no! Do you recommend a different F/OSS app for similar functionality? I was thinking something like veracrypt, maybe?

**Comment by iPyGuy** [comment]
Veracrypt is fine, it's just far more bloated than Picocrypt, hence the "pico" in the name. I hope Picocrypt isn't being discontinued now...

**Comment by vraravam** [comment]
> Veracrypt is fine, it's just far more bloated than Picocrypt, hence the "pico" in the name.

Yes, I do realize that. And that's why I was trying out Picocrypt in the first place 😄

**Comment by HACKERALERT** [comment]
VeraCrypt is the best next choice but it is more complicated to use for sure which is part of the reason I made Picocrypt. Times have changed though and I'm starting to set the project aside now. To be clear, it's still a completely usable and secure software when it runs, but unfortunately it will probably break on macOS in the near future and I don't want to fix it (it'll need a complete rewrite of the UI put simply) so I would advise against using Picocrypt GUI if you're on a Mac. The CLI will continue to work fine on macOS.
