### ISSUE TITLE
[Feature Request] PGP Messaging, ezpz, 1, 2, 3

### ISSUE THREAD

**Issue by BuildBackBuehler** [Picocrypt/Picocrypt#54]
I hope I wasn't speedreading _too fast_, but this didn't seem to be apart of PC. Now that I think about it, I do think this'd be better off done as it's own thang, just in the same vain as PC! Ala Objective See w/ Lulu, Block Block, Knockin', etc. (well, TBH I wish some of their absurdly smole, overlapping/natural compliment-type apps were combined, but I do think Picocrypt has a nice medley of features that hide your arse no matter what farce you may be in, so you've got my vote of confidence FWIW, (nothing))

Y'anyways, of all the things on the laundry list of opsec/privacy, PGP Messaging is the absolute worst. The 2 or 3 exes I'd given a try in the past were clunky, unintuitive and *hopefully* unnecessarily complicated. I haven't used PGP in a couple years...but I doubt anything has changed. Kleopatra comes to mind. 

I think 1 of the cruxes of these things is the limitlessness of it. Namely, I don't want to create 5 dang identities all with different keypasses and passphrases that I cannot keep track of, let alone following along with where the heck the unencrypted message is to be opened...then opening up another file to create my message back. Then pick the right identity (my own fault but I'd end up with a non-functional 1, just start up a new one, can't/didn't bother with the removal process). 

Something with continuity and perhaps also a nice, streamlined workflow. It'd be awesome as heck to have a message that I just closed after encrypting to come with a metadata file (yeah, yeah, an identifying doc. attached to a private note, an oxymoronic thought from a moron at surface level). This helper file would keep the encrypting & decrypting sig. blocks around so you can pickup where you left off if you forgot to add the milk on your encrypted, hyperprivate grocery list. So you start looking through the Supermarket's food/drinks, end up copying and pasting a link when the neglected milk runs through your head. Normally you'd be forced to hop onto Encryptedbook to find this person's PGP block, but no worries, metadata file! 

Perhaps an underlying mech. could be to obfuscate which metadata file belongs to which conversation. The user is prompted to provide whatever authentication they'd setup and bam the fog of war is lifted, the metadata files are linked respectively and all you had to do was enter the 6 digits from your authenticator app (another hugely disappointing group of solutions if I might add 😂...but, another time). 

Came to mind just because of the fraction of the blurb mentioning encrypting your comments/meta-notes and for a sec. got all excited, the end. Hope its handy or inspires somethin' otherwise what was all this rambling procrastination-driven TEDx Talk for?

**Comment by hakavlad** [comment]
>PGP Messaging

Do you need messenger or file encryption tool?

**Comment by HACKERALERT** [comment]
A bit too much work... also not exactly file encryption :)
