### ISSUE TITLE
Potential Virus Total Findings

### ISSUE THREAD

**Issue by link-leo** [Picocrypt/Picocrypt#59]
Downloaded the Win.exe and ran through Virus Total, potential findings for Bkav Pro and Cylance. Curious about this. See here: [VirusTotal](https://www.virustotal.com/gui/file/4388c47832b509d898236632502127b6f0805a3192d9a9ab297bb073bc94fed5)

**Comment by Retengart** [comment]
This is called "false detection" from some noname antiviruses

**Comment by HACKERALERT** [comment]
tbf, an executable that is packed with upx and contains cryptography code and ability to delete files does somewhat look like ransomware. But yeah it's been like this since the start and is the same for basically every other open source project, just have to ignore some.
