### ISSUE TITLE
"Picocrypt.app" is damaged and can't be opened.

### ISSUE THREAD

**Issue by Ozwel** [Picocrypt/Picocrypt#64]
Hi,

The .dmg file from release 1.43 cannot be run on macOS Sequoia (maOS 15.0), at least on ARM/Silicon processors.
Any plan to have it ready to run on Apple Silicon chips?

Also, can't macOS run an x86 .dmg with roseta? Why can't macOS run this 1.43 release?

**Comment by Retengart** [comment]
Picocrypt has been running on ARM/Silicon processors since 1.34. So I don't know why you have this problem
