### ISSUE TITLE
Decrypting multiple files

### ISSUE THREAD

**Issue by DHYTFG** [Picocrypt/Picocrypt#66]
Is it possible to decrypt several files at once with your program? I dragged files into the program window but only the first file is decrypted.

**Comment by Retengart** [comment]
@DHYTFG Answer by HACKERALERT:
You can decrypt multiple volumes at the same time, just put them in a folder, drop the folder, enter the password and toggle Recursive. It looks like it is encrypting but it will decrypt. This is documented in the GUI README under the Recursive feature.

**Comment by DHYTFG** [comment]
Thank you and I apologize for my inability to read instructions.
