### ISSUE TITLE
Broken Package

### ISSUE THREAD

**Issue by DSS87** [Picocrypt/Picocrypt#67]
Hello, I am using Linux Mint Debian Cinnamon Muffin v: 6.2.0. I installed the .deb package but it is broken.

Error message: "You have 1 broken package on your system. Use "Broken" filter to get locate it."

**Comment by Retengart** [comment]
Hmm, weird situation. Does binary or Flatpak version of Picocrypt work for you?

**Comment by DSS87** [comment]
I was able to repair the package using Synaptic. It works, thanks. :)

**Comment by HACKERALERT** [comment]
For future reference, also try `sudo apt-get -f install`.
